FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 6801

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["BasicsService/BasicsService.csproj", "BasicsService/"]
RUN dotnet restore "BasicsService/BasicsService.csproj"
COPY . .
WORKDIR "/src/BasicsService"
RUN dotnet build "BasicsService.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "BasicsService.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "BasicsService.dll"]